#!/usr/bin/env python3
"""从已确认的 deploy-inputs.json 幂等生成应用侧部署清单。"""

from __future__ import annotations

import argparse
import json
import os
import re
import tempfile
from pathlib import Path


DNS_LABEL = re.compile(r"^[a-z0-9](?:[-a-z0-9]*[a-z0-9])?$")
DNS_HOST = re.compile(r"^(?=.{1,253}$)(?:[a-z0-9](?:[-a-z0-9]*[a-z0-9])?\.)+[a-z0-9](?:[-a-z0-9]*[a-z0-9])?$")
IMAGE_REF = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/:@+-]*$")
HTTP_PATH = re.compile(r"^/[A-Za-z0-9._~!$&()*+;=:@%/-]*$")
STORAGE_SIZE = re.compile(r"^[1-9][0-9]*(?:Mi|Gi|Ti)$")
ALLOWED_WORKLOADS = {"stateless", "stateful", "worker", "migration"}
MARKER = "# Generated by production-devops-sre; edit deploy-inputs.json and regenerate.\n"
SKILL_DIR = Path(__file__).resolve().parent.parent
TEMPLATES = SKILL_DIR / "assets" / "templates" / "kubernetes"
WRITTEN: set[Path] = set()
OUTPUT_ROOT: Path | None = None


def fail(message: str) -> None:
    raise ValueError(message)


def validate(data: dict) -> None:
    if data.get("schema_version") != 1:
        fail("schema_version 必须为 1")
    for field in ("project", "namespace"):
        value = data.get(field, "")
        if len(value) > 63 or not DNS_LABEL.fullmatch(value):
            fail(f"{field} 必须是合法的小写 DNS 标签")
    services = data.get("services")
    if not isinstance(services, list) or not services:
        fail("services 必须是非空数组")
    domain = data.get("domain", "")
    if not (isinstance(domain, str) and (domain == "<DOMAIN_PENDING_APPROVAL>" or DNS_HOST.fullmatch(domain))):
        fail("domain 必须是合法域名或明确占位符")
    names = set()
    ingress_paths = set()
    for service in services:
        name = service.get("name", "")
        if len(name) > 63 or not DNS_LABEL.fullmatch(name) or name in names:
            fail(f"服务名不合法或重复：{name!r}")
        names.add(name)
        if service.get("workload") not in ALLOWED_WORKLOADS:
            fail(f"{name}: workload 必须是 {sorted(ALLOWED_WORKLOADS)} 之一")
        image = service.get("image", "")
        if not isinstance(image, str) or not (image == "<IMAGE_DIGEST_REQUIRED>" or IMAGE_REF.fullmatch(image)):
            fail(f"{name}: image 不合法")
        if service["workload"] != "migration":
            port = service.get("port")
            if not isinstance(port, int) or not 1 <= port <= 65535:
                fail(f"{name}: port 必须在 1..65535")
        for field in ("uid", "gid"):
            if not isinstance(service.get(field), int) or service[field] < 10000:
                fail(f"{name}: {field} 必须是不低于 10000 的整数")
        for field in ("health_path", "ready_path"):
            path = service.get(field)
            if service["workload"] in {"stateless", "stateful"} and (not isinstance(path, str) or not HTTP_PATH.fullmatch(path)):
                fail(f"{name}: {field} 不是安全的 HTTP 路径")
        if service["workload"] == "worker" and not service.get("probe_command"):
            fail(f"{name}: worker 必须提供 probe_command，不能虚构 HTTP 探针")
        if service["workload"] in {"stateless", "stateful"} and not service.get("compose_healthcheck"):
            fail(f"{name}: 必须提供经过镜像验证的 compose_healthcheck")
        if service["workload"] == "migration" and not service.get("migration_command"):
            fail(f"{name}: migration 必须提供 migration_command")
        if service.get("expose"):
            ingress_path = service.get("ingress_path")
            if service["workload"] not in {"stateless", "stateful"}:
                fail(f"{name}: 只有 HTTP 服务可以 expose")
            if not isinstance(ingress_path, str) or not HTTP_PATH.fullmatch(ingress_path) or ingress_path in ingress_paths:
                fail(f"{name}: ingress_path 必须是安全且唯一的 HTTP 路径")
            ingress_paths.add(ingress_path)
        if service["workload"] == "stateful":
            if not isinstance(service.get("data_path"), str) or not HTTP_PATH.fullmatch(service["data_path"]) or service["data_path"] == "/":
                fail(f"{name}: stateful 必须提供安全的 data_path")
            if not isinstance(service.get("storage_size"), str) or not STORAGE_SIZE.fullmatch(service["storage_size"]):
                fail(f"{name}: storage_size 必须使用 Mi/Gi/Ti，例如 10Gi")


def atomic_write(path: Path, text: str, marker: bool = True) -> None:
    resolved = path.resolve()
    if OUTPUT_ROOT is None or not resolved.is_relative_to(OUTPUT_ROOT):
        fail(f"拒绝写入输出目录之外：{path}")
    WRITTEN.add(resolved)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        fail(f"拒绝覆盖符号链接：{path}")
    rendered = (MARKER if marker else "") + text.rstrip() + "\n"
    if path.exists() and path.read_text(encoding="utf-8") == rendered:
        return
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(rendered)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def template(name: str, values: dict[str, object]) -> str:
    text = (TEMPLATES / name).read_text(encoding="utf-8")
    for key, value in values.items():
        text = text.replace(f"__{key}__", str(value))
    remaining = sorted(set(re.findall(r"__[A-Z0-9_]+__", text)))
    if remaining:
        fail(f"模板 {name} 仍有未提供变量：{', '.join(remaining)}")
    return text


def rendered_image(service: dict) -> str:
    if service["image"] == "<IMAGE_DIGEST_REQUIRED>":
        return f"image-pending-approval.invalid/{service['name']}:pending"
    return service["image"]


def compose(data: dict) -> str:
    lines = [f"name: {data['project']}", "services:"]
    volumes = []
    for service in data["services"]:
        name = service["name"]
        image = rendered_image(service)
        if service["workload"] == "migration":
            lines.extend([
                f"  {name}:", f"    image: \"{image}\"", "    profiles: [migration]",
                "    restart: \"no\"", f"    user: \"{service['uid']}:{service['gid']}\"",
                "    read_only: true", "    cap_drop: [ALL]", "    security_opt: [\"no-new-privileges:true\"]",
                "    networks: [app-internal]", "    command: " + json.dumps(service["migration_command"], ensure_ascii=False),
            ])
            continue
        port = service["port"]
        lines.extend([
            f"  {name}:", f"    image: \"{image}\"", "    init: true", "    restart: unless-stopped",
            f"    user: \"{service['uid']}:{service['gid']}\"", "    read_only: true",
            "    cap_drop: [ALL]", "    security_opt: [\"no-new-privileges:true\"]",
            "    pids_limit: 200", "    mem_limit: 512m", "    cpus: \"1.0\"",
            "    environment:", "      LOG_LEVEL: INFO", "      TZ: Asia/Shanghai",
            "    tmpfs: [\"/tmp:rw,noexec,nosuid,nodev,size=64m,mode=1777\"]",
            "    networks: [app-internal]",
        ])
        if service["workload"] != "worker":
            lines.extend([
                "    ports:", f"      - \"127.0.0.1:${{{name.upper().replace('-', '_')}_PORT:-{port}}}:{port}\"",
                "    healthcheck:", "      test: " + json.dumps(service["compose_healthcheck"], ensure_ascii=False),
                "      interval: 30s", "      timeout: 5s", "      retries: 3", "      start_period: 20s",
            ])
        else:
            command = ", ".join(json.dumps(str(part)) for part in service["probe_command"])
            lines.extend(["    healthcheck:", f"      test: [CMD, {command}]", "      interval: 30s", "      timeout: 5s", "      retries: 3"])
        if service["workload"] == "stateful":
            volume = f"{name}-data"
            volumes.append(volume)
            lines.extend(["    volumes:", f"      - \"{volume}:{service['data_path']}\""])
        lines.extend(["    logging:", "      driver: local", "      options: {max-size: \"100m\", max-file: \"3\"}"])
    lines.extend(["networks:", "  app-internal:", "    name: " + data["project"] + "-internal"])
    if volumes:
        lines.append("volumes:")
        for volume in volumes:
            lines.extend([f"  {volume}:", f"    name: {data['project']}-{volume}"])
    return "\n".join(lines)


def main() -> int:
    global OUTPUT_ROOT
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("--output", type=Path, default=Path("deploy"))
    args = parser.parse_args()
    data = json.loads(args.input.read_text(encoding="utf-8"))
    validate(data)
    output = args.output.resolve()
    if output.is_symlink():
        fail(f"拒绝使用符号链接输出目录：{output}")
    OUTPUT_ROOT = output
    index_path = output / ".sre-generated-files.json"
    try:
        previous = set(json.loads(index_path.read_text(encoding="utf-8"))) if index_path.exists() else set()
    except (OSError, json.JSONDecodeError, TypeError):
        previous = set()
    atomic_write(output / "docker-compose.yml", compose(data))
    ns = data["namespace"]
    common = {"PROJECT": data["project"], "NAMESPACE": ns}
    resources = ["namespace.yaml"]
    atomic_write(output / "k8s/namespace.yaml", template("namespace.yaml.tpl", common))
    domain = data.get("domain") or "<DOMAIN_PENDING_APPROVAL>"
    if domain.startswith("<"):
        domain = "domain-pending-approval.invalid"
    domain_approved = not domain.endswith(".invalid") and not str(data.get("domain_request", "")).startswith("<")
    ingress_services = []
    for service in data["services"]:
        name = service["name"]
        workload = service["workload"]
        values = common | {
            "NAME": name, "IMAGE": rendered_image(service), "PORT": service.get("port", 8080),
            "UID": service["uid"], "GID": service["gid"],
            "HEALTH_PATH": service.get("health_path", "/healthz"),
            "READY_PATH": service.get("ready_path", "/readyz"),
            "DATA_PATH": service.get("data_path") or "/data",
            "STORAGE_SIZE": service.get("storage_size") or "10Gi",
            "DOMAIN": domain,
            "DOMAIN_APPROVAL": "approved" if domain_approved else "pending",
            "TLS_SECRET": f"{name}-tls" if domain_approved else f"{name}-tls-pending-operations",
            "INGRESS_PATH": service.get("ingress_path", "/"),
            "MIGRATION_COMMAND": json.dumps(service.get("migration_command", ["/app/migrate"]), ensure_ascii=False),
        }
        atomic_write(output / f"k8s/{name}-service-account.yaml", template("service-account.yaml.tpl", values))
        resources.append(f"{name}-service-account.yaml")
        if workload == "migration":
            atomic_write(output / f"k8s/{name}-job.yaml", template("migration-job.yaml.tpl", values))
            resources.append(f"{name}-job.yaml")
            continue
        atomic_write(output / f"k8s/{name}-configmap.yaml", template("configmap.yaml.tpl", values))
        resources.append(f"{name}-configmap.yaml")
        if workload == "worker":
            values["PROBE_COMMAND"] = json.dumps(service["probe_command"], ensure_ascii=False)
            workload_template = "worker-deployment.yaml.tpl"
        elif workload == "stateful":
            workload_template = "statefulset.yaml.tpl"
        else:
            workload_template = "deployment.yaml.tpl"
        suffix = "statefulset" if workload == "stateful" else "deployment"
        atomic_write(output / f"k8s/{name}-{suffix}.yaml", template(workload_template, values))
        resources.append(f"{name}-{suffix}.yaml")
        if workload != "worker":
            atomic_write(output / f"k8s/{name}-service.yaml", template("service.yaml.tpl", values))
            resources.append(f"{name}-service.yaml")
            if service.get("expose"):
                ingress_services.append((name, values))
        if workload == "stateful":
            atomic_write(output / f"k8s/{name}-headless-service.yaml", template("headless-service.yaml.tpl", values))
            resources.append(f"{name}-headless-service.yaml")
        if workload == "stateless":
            atomic_write(output / f"k8s/{name}-pdb.yaml", template("pdb.yaml.tpl", values))
            resources.append(f"{name}-pdb.yaml")
        atomic_write(output / f"k8s/{name}-network-policy.yaml", template("network-policy.yaml.tpl", values))
        resources.append(f"{name}-network-policy.yaml")
    for name, values in ingress_services:
        atomic_write(output / f"k8s/{name}-ingress.yaml", template("ingress.yaml.tpl", values))
        resources.append(f"{name}-ingress.yaml")
    kustomization = "apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources:\n" + "".join(f"  - {item}\n" for item in resources)
    atomic_write(output / "k8s/kustomization.yaml", kustomization)
    unconfirmed = {service["name"]: service.get("requires_confirmation", []) for service in data["services"] if service.get("requires_confirmation")}
    atomic_write(output / "release-gate.json", json.dumps({
        "change_ticket": data.get("change_ticket"), "domain_request": data.get("domain_request"),
        "domain": data.get("domain"), "first_cicd_approved": data.get("first_cicd_approved", False),
        "external_access": bool(ingress_services),
        "reviewer": "于海龙或其正式授权的 SRE 代理人",
        "unconfirmed": unconfirmed,
    }, ensure_ascii=False, indent=2), marker=False)
    current = {str(path.relative_to(output)) for path in WRITTEN if path.is_relative_to(output)}
    for relative in sorted(previous - current):
        stale = (output / relative).resolve()
        if not stale.is_relative_to(output):
            continue
        if stale.is_file() and not stale.is_symlink():
            try:
                if stale.read_text(encoding="utf-8").startswith(MARKER):
                    stale.unlink()
            except OSError:
                pass
    atomic_write(index_path, json.dumps(sorted(current), ensure_ascii=False, indent=2), marker=False)
    print(f"已在 {output} 收敛生成 {len(current)} 个文件")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
